### ISSUE TITLE
Use Plots.jl for plotting

### ISSUE THREAD

**Issue by dpsanders** [Datseris/DynamicalBilliards.jl#2]
I suggest to consider using [Plots.jl](https://github.com/tbreloff/Plots.jl), rather than straight `PyPlot` for plotting.

This has a few benefits:
- Allows to use various backends
- Has `@gif` for automatically generating GIFs.

(The current plotting looks very nice, though!)

**Comment by Datseris** [comment]
Thank you for the suggestion, I also want to do that (to switch to Plots). I have never used `Plots.jl` before though, so I have to learn it a bit first before making the change. 

The good thing is that the plotting functions are all in `PlotBilliards.jl` and they are very few, so it won't be hard. But this will be done after some official Docs are created. 
(of course if you know to move around with Plots and want to submit any PRs go ahead!)

**Comment by Datseris** [comment]
I am closing this, since the latest release has the PyPlot dependency.

Unfortunately the Plots package not only does not have nearly as much power as PyPlot but also has really insufficient documentation. 

The entire idea was for users to pass keywords directly into the plotting functions, which can achieved with both packages, but PyPlot (matplotlib) simply has much superior documentation, making it easy for a user that may not know about either of the two packages.

In addition, a crucial feature necessary for plotting a particle (that plotted arrows do not change scale when zooming in) is missing from Plots and not even the creator knew how to do it.
